### ISSUE TITLE
Failed to mvn clean package (could not resolve dependencies)

### ISSUE THREAD

**Issue by mattplindsay** [dstl/baleen3#4]
After having done a clean clone of the repository, and runnin `mvn clean package` I get the following:

`[INFO] -------------------------< uk.gov.dstl:baleen >-------------------------
[INFO] Building Baleen 3 3.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.annot8:annot8-conventions:jar:1.1.0 is missing, no dependency information available
[WARNING] The POM for io.annot8:annot8-components-geo:jar:1.1.0 is missing, no dependency information available
[WARNING] The POM for io.annot8:annot8-components-print:jar:1.1.0 is missing, no dependency information available
`
Then following this: 
`Failed to execute goal on project baleen: Could not resolve dependencies for project uk.gov.dstl:baleen:jar:3.0.2: The following artifacts could not be resolved: io.annot8:annot8-conventions:jar:1.1.0, io.annot8:annot8-components-geo:jar:1.1.0, io.annot8:annot8-components-print:jar:1.1.0: Failure to find io.annot8:annot8-conventions:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced `

The expected result would have been a build success.

Current build environment is Ubuntu 20.04 but have also tried it as part of a dockerfile (which was from ubuntu:latest - which is probably also Ubuntu 20.04)

Does anyone know what's causing this? Does anyone else get a build success using this build or even commit a1739ed3d83df3ce265296009eca88fe150b6203 (which I thik is the last release version)?

**Comment by jbaker-dstl** [comment]
This is due to another project, https://github.com/annot8/annot8-components, having released v1.1.0 but not yet pushed them to Maven Central. I will follow up and try and get this done (from memory, I think there was an issue with Maven Central when they tried initially).

Checking out the latest version of that project locally and doing a `mvn clean install` prior to building Baleen 3, should work as a temporary workaround I believe.

**Comment by jbaker-dstl** [comment]
v1.1.0 has now been pushed up to Maven Central (though it might take an hour or so for them to sync to mirrors). @mattplindsay - could you try building again and seeing if it works now?

**Comment by mattplindsay** [comment]
All seems to work pretty well now, thanks!
